apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-frontend
  labels:
    app: food-delivery-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-delivery-frontend
  template:
    metadata:
      labels:
        app: food-delivery-frontend
    spec:
      containers:
        - name: food-delivery-frontend
          image: jeevankumar01/food-delivery-frontend:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
