apiVersion: v1
kind: Service
metadata:
  name: food-delivery-frontend-service
spec:
  selector:
    app: food-delivery-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
